export const ACCESS_TOKEN = 'token' // 用户token
export const SIDEBAR_TYPE = 'SIDEBAR_TYPE' // 导航条类型
export const DEFAULT_THEME = 'DEFAULT_THEME' // 暗和亮主题
export const DEFAULT_LAYOUT_MODE = 'DEFAULT_LAYOUT_MODE' // 设置导航条在上方还是在侧边
export const DEFAULT_COLOR = 'DEFAULT_COLOR' // 默认颜色
export const DEFAULT_COLOR_WEAK = 'DEFAULT_COLOR_WEAK'
export const DEFAULT_FIXED_HEADER = 'DEFAULT_FIXED_HEADER'
export const DEFAULT_FIXED_SIDEMENU = 'DEFAULT_FIXED_SIDEMENU'
export const DEFAULT_FIXED_HEADER_HIDDEN = 'DEFAULT_FIXED_HEADER_HIDDEN'
export const DEFAULT_CONTENT_WIDTH_TYPE = 'DEFAULT_CONTENT_WIDTH_TYPE'
export const DEFAULT_MULTI_TAB = 'DEFAULT_MULTI_TAB'

export const CONTENT_WIDTH_TYPE = {
  Fluid: 'Fluid',
  Fixed: 'Fixed'
}
